version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    networks:
      - net

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-app
    restart: always
    depends_on:
      - fastapi-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      FASTAPI_URL: "http://fastapi-app:8000"
    networks:
      - net

networks:
  net:
    driver: bridge
